version: '3'

networks:
    proxy:
      external:
        name: sell_proxy
    db-net:
      external:
        name: sell_dbnet

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - db-net
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -s --database=$$MYSQL_DATABASE -e 'SHOW TABLES;'"
      interval: 30s
      timeout: 3s
      retries: 2

  wp:
    build: .
    depends_on:
      - db
    restart: always
    volumes:
      - ./html:/var/www/html:rw
    networks:
      - proxy
      - db-net
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WP_TABLE_PREFIX
      VIRTUAL_HOST: $DOMAIN_NAME
      VIRTUAL_PORT: $VIRTUAL_PORT
      LETSENCRYPT_HOST: $DOMAIN_NAME
      LETSENCRYPT_EMAIL: $V_LETSENCRYPT_EMAIL
    healthcheck:
      test: "curl -Ls -o /dev/null -w \"%{http_code}\n%{url_effective}\n\" http://localhost:$$VIRTUAL_PORT"
      interval: 30s
      timeout: 3s
      retries: 2
